update gpm and readme

diff --git a/.tools/gpm b/.tools/gpm
--- a/.tools/gpm
+++ b/.tools/gpm
@@ -1,8 +1,5 @@
 #!/usr/bin/env bash
 
-## Copyright (c) 2013 Pablo Astigarraga
-## https://github.com/pote/gpm
-
 set -eu
 
 ## Functions/
@@ -26,7 +23,7 @@ SYNOPSIS
 
     gpm has a companion tool, called [gvp](https://github.com/pote/gvp) which
     provides vendoring functionalities, it alters your GOPATH so every project
-    has its own isolated dependency directory, it's usage is recommended.
+    has its own isolated dependency directory, its usage is recommended.
 
 USAGE
       $ gpm             # Same as 'install'.
@@ -41,6 +38,13 @@ is_in_use() {
   [[ -e "$1/.git/index.lock" || -e "$1/.hg/store/lock"  || -e "$1/.bzr/checkout/lock" ]]
 }
 
+# Exit with an error message to stderr. An optional second argument sets the
+# exit status (defaults to `1`).
+abort() {
+	echo "$1" >&2;
+	exit ${2:-1};
+}
+
 # Iterates over Godep file dependencies and sets
 # the specified version on each of them.
 set_dependencies() {
@@ -48,28 +52,33 @@ set_dependencies() {
 
   while read package version; do
     (
+      echo ">> Getting package "$package""
+      go get -u -d "$package"
+    ) &
+  done < <(echo "$deps")
+  wait
+
+  while read package version; do
+    (
       local pkg_path=$(echo "$package" | awk -F/ '{print $1"/"$2"/"$3}')
       local install_path="${GOPATH%%:*}/src/${pkg_path%%/...}"
-      echo ">> Getting package "$package""
-
-      # Retries in case of possible race conditions when installing a package
-      # dependency
-      for ((i=0; i<5; i++)); do
-        out=$(go get -u -d "$package" 2>&1 >/dev/null) && break
-      done
-      [[ $? != 0 ]] && echo "-- Failed to get "$package", error: " && echo "$out" && exit 1
-
       echo ">> Setting $package to version $version"
       cd $install_path
       is_in_use $install_path && wait
 
-      [ -d .hg  ] && hg update    -q      "$version"
-      [ -d .git ] && git checkout -q      "$version"
       [ -d .bzr ] && bzr revert   -q -r   "$version"
+      [ -d .git ] && git checkout -q      "$version"
+      [ -d .hg  ] && hg update    -q      "$version"
       [ -d .svn ] && svn update   -r      "$version"
     ) &
   done < <(echo "$deps")
   wait
+
+  while read package version; do
+    echo ">> Building package "$package""
+    go install "$package"
+  done < <(echo "$deps")
+
   echo ">> All Done"
 }
 ## /Functions
@@ -77,13 +86,14 @@ set_dependencies() {
 ## Command Line Parsing
 case "${1:-"install"}" in
   "version")
-    echo ">> gpm v1.2.3"
+    echo ">> gpm v1.3.2"
     ;;
   "install")
     deps_file="${2:-"Godeps"}"
-    [[ -r "$deps_file" ]] || (echo ">> $deps_file file does not exist." && exit 1)
+    [[ -r "$deps_file" ]] || abort ">> $deps_file file does not exist."
     (which go > /dev/null) ||
-      ( echo ">> Go is currently not installed or in your PATH" && exit 1)
+      abort ">> Go is currently not installed or in your PATH"
+    [ -z "${GOPATH:-}" ] && abort ">> GOPATH is not set"
     set_dependencies $deps_file
     ;;
   "help")
@@ -98,7 +108,7 @@ case "${1:-"install"}" in
       gpm-$plugin $@ &&
       exit
     else
-      echo ">> No command 'gpm $1'"
+      echo ">> No command 'gpm $1'" >&2
       usage && exit 1
     fi
     ;;
